version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery_app
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=delivery_service
      - JWT_SECRET=SosIk
      - PORT=8080
      - ALLOWED_ORIGINS=http://localhost:3000,https://practice-2025.vercel.app,https://practice-2025-git-main.vercel.app,https://practice-2025-*.vercel.app,http://92.246.76.171:8080,http://92.246.76.171
    ports:
      - "8080:8080"

volumes:
  postgres_data: 